-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 09:44:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb` DEFAULT CHARACTER SET utf8 ;
USE `airbnb` ;

-- -----------------------------------------------------
-- Table `airbnb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `super_host` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(1000) NOT NULL,
  `image` TEXT NULL,
  `content` TEXT NOT NULL,
  `price` BIGINT UNSIGNED NOT NULL,
  `rating` TINYINT UNSIGNED NOT NULL,
  `host_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accommodation_user1_idx` (`host_id` ASC),
  CONSTRAINT `fk_accommodation_user1`
    FOREIGN KEY (`host_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`reservation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `person_count` TINYINT NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `accommodation_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_user_idx` (`user_id` ASC),
  INDEX `fk_reservation_accommodation1_idx` (`accommodation_id` ASC) ,
  CONSTRAINT `fk_reservation_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservation_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb`.`option` (
  `accommodation_id` INT UNSIGNED NOT NULL,
  `whole_house` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `private_room` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `hotel_rool` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `multi-person_room` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `room_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `bed_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `bathroom_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `min_people` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `max_people` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  INDEX `fk_option_accommodation1_idx` (`accommodation_id` ASC),
  PRIMARY KEY (`accommodation_id`),
  CONSTRAINT `fk_option_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
