version: '3.3'

services:
  db:
    container_name: mysql-airbnb
    image: mysql:5.7
    restart: always
    # networks:
    #   - UDN_Database
    ports:
      - 9999:3306
    volumes:
      - /home/root/docker/mysql/data:/var/lib/mysql
      - /home/root/docker/mysql/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
    command: 
      --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    # command : 
    #   - mysql -u root -p rjsdnrkkw4809!! 
# networks:
#   UDN_Database:
#     external:
#       name: UDN_Database
#   UDN_Service:
#     external:
#       name: UDN_Service
